import { Geist, Geist_Mono, Play } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const play = Play({
  variable: "--font-play", 
  subsets: ['latin'],
  weight: ['400', '700'], 
  display: 'swap'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${play.variable} ${geistMono.variable} antialiased bg-[#060606]`}>
        {children}
      </body>
    </html>
  );
}
